### ISSUE TITLE
Use links from jsdelivr

### ISSUE THREAD

**Issue by borkdude** [kloimhardt/babashka-scittle-guestbook#1]
Hey @kloimhardt, thanks for the great project.

I just published versioned artifacts of scittle to jsdelivr:

https://github.com/borkdude/scittle/releases/tag/v0.0.1

Please use these links, so we can safely change the hosted files on github pages without breaking your project.

**Comment by kloimhardt** [comment]
For the Clojure codebase: this change of links already altered nearly 5% of it :-) 
For the Clojurescript codebase: it is entirely stolen from Luminus :-))
